### ISSUE TITLE
Question about utilizing your PicoLogic code

### ISSUE THREAD

**Issue by kmatch98** [markb139/pico_logic#6]
I just submitted my [first pull request for the TinyLogicFriend driver for sigrok/PulseView](https://github.com/sigrokproject/libsigrok/pull/137).  I think it has most of the commands needed to interact with a decent set of boards.  

I did my [first set of the TinyLogicFriend firmware with the Atmel/SAMD Cortex M4 boards](https://github.com/kmatch98/tinylogicfriend). Now with the capabilities you’ve shown for the Raspberry Pi RP2040, I want to work on connecting with the RP2040 next. 

If possible, I’d like to work with your code, but before I do that I wanted to clarify the License for your code. Can you please update with your license for your PicoLogic project? I just want to be sure I’m using code that matches with the objective of keeping the TinyLogicFriend as open as possible. 

Best regards, Kevin (kmatch98)

**Comment by markb139** [comment]
Hi,
I've added the GPL 3 license.

Regards
Mark
